#!/bin/bash

# Import the workspace
jupyter lab workspaces import binder/jupyterlab-workspace.json

# wrap in a function to avoid overwriting the global $1, $2, etc.


cp binder/jupyterlab-workspace.json $HOME/.jupyter/lab/workspaces/default-37a8.jupyterlab-workspace

exec "$@"